### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by SebastianHafner** [AngieNikki/openWUSU#1]
Hi,

Congrats on the very interesting paper & dataset.

I was wondering when the dataset will be available. I would really like to use it for my research.

Best,
Sebastian

**Comment by AngieNikki** [comment]
Thank you for your interest and reminder. The data download link has been uploaded. Due to certain reasons, the data had to be released in patches. Apologies for any inconvenience.

**Comment by SebastianHafner** [comment]
Got the data. Thanks a lot!
